# Generated by Django 3.2 on 2021-12-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_data',
            name='channel_title',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='youtube_data',
            name='channel_url',
            field=models.URLField(default='None'),
        ),
        migrations.AddField(
            model_name='youtube_data',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
